"""The (20, 10) linear block code used to encode a 4x5 protein-position grid.

Why exact codebook enumeration instead of a decoding "circuit": with k=10,
the full codebook has only 2**10 = 1024 codewords, so exact posterior
inference over codewords (decoding.py) is one dense vectorized computation
per batch, not an approximation. That's cheaper to build and just as fast as
compiling a trellis/factor-graph circuit would be at this size. Revisit if k
grows past roughly 20-24, where 2**k enumeration stops being cheap and a
proper trellis (BCJR-style forward-backward) circuit would pay for itself.

The old_stuff/NEO_ECC/neo.py version hardcoded H and G as two separately
typed-out matrices and only checked after the fact that they were consistent
-- twice the numbers to transcribe, twice the chance of a silent error. Here
there's one source of truth (the P submatrix) and G/H are derived from it.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from neo_toolkit.ecc import gf2

# P submatrix of the systematic generator G = [I_10 | P] for a (20, 10)
# code with minimum distance 6 (verified in tests/ecc/test_code.py).
# Carried over as-is from old_stuff/NEO_ECC/neo.py's hardcoded G/H --
# finding a code with equal or better distance is a separate search problem
# -- but every structural property claimed about it is now verified by a
# test rather than assumed.
_P = np.array(
    [
        [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 1, 1, 0, 0, 0],
        [1, 1, 0, 1, 0, 1, 0, 1, 0, 0],
        [1, 0, 1, 0, 1, 0, 1, 1, 0, 0],
        [1, 0, 1, 1, 0, 1, 0, 0, 1, 0],
        [0, 1, 1, 0, 1, 0, 1, 0, 1, 0],
        [1, 1, 1, 0, 1, 1, 0, 1, 1, 0],
        [1, 1, 0, 1, 1, 0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
        [0, 1, 1, 1, 0, 1, 0, 0, 0, 1],
    ],
    dtype=np.uint8,
)


@dataclass(frozen=True)
class LinearCode:
    """A binary (n, k) linear block code in systematic form G = [I_k | P]."""

    G: np.ndarray  # (k, n) uint8
    H: np.ndarray  # (n - k, n) uint8
    codebook: np.ndarray = field(repr=False)  # (2**k, n) uint8

    @property
    def k(self) -> int:
        return self.G.shape[0]

    @property
    def n(self) -> int:
        return self.G.shape[1]

    def encode(self, messages: np.ndarray) -> np.ndarray:
        """Encode a batch of length-k bit messages, shape (..., k) -> (..., n)."""
        return gf2.matmul(messages, self.G)

    def is_codeword(self, words: np.ndarray) -> np.ndarray:
        """Check a batch of length-n bit vectors against the parity checks."""
        syndrome = gf2.matmul(words, self.H.T)
        return ~np.any(syndrome, axis=-1)

    def minimum_distance(self) -> int:
        """Minimum Hamming distance: for a linear code, the minimum nonzero weight."""
        weights = self.codebook.sum(axis=1)
        return int(weights[weights > 0].min())


def from_systematic_parity(P: np.ndarray) -> LinearCode:
    """Build a LinearCode from the P block of a systematic G = [I_k | P]."""
    k, r = P.shape
    n = k + r
    G = np.hstack([np.eye(k, dtype=np.uint8), P.astype(np.uint8)])
    H = np.hstack([P.T.astype(np.uint8), np.eye(r, dtype=np.uint8)])
    codebook = build_codebook(G)
    return LinearCode(G=G, H=H, codebook=codebook)


def build_codebook(G: np.ndarray) -> np.ndarray:
    """Encode every message 0..2**k-1, fully vectorized (no per-codeword loop)."""
    k = G.shape[0]
    messages = np.arange(2**k, dtype=np.uint32)
    bits = ((messages[:, None] >> np.arange(k - 1, -1, -1)) & 1).astype(np.uint8)
    return gf2.matmul(bits, G)


def verify(code: LinearCode) -> None:
    """Raise AssertionError if `code` isn't a well-formed systematic linear code.

    Equivalent to (but O(k*n^2) instead of O(2**n)) checking that exactly
    2**k of the 2**n possible bit vectors satisfy the parity checks: that
    holds iff H's rows are independent (rank n-k, so the solution space has
    exactly 2**k elements) and every codeword actually satisfies H (H @ G.T
    == 0, so the code generated by G is contained in the null space of H).
    """
    k, n = code.k, code.n
    assert gf2.rank(code.G) == k, "G must have full row rank k"
    assert gf2.rank(code.H) == n - k, "H must have full row rank n-k"
    assert not np.any(gf2.matmul(code.H, code.G.T)), "every codeword must satisfy H"


NEO_20_10 = from_systematic_parity(_P)
